/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICertifier,
  ICertifierInterface,
} from "../../../../dms-osx-artifacts/contracts/interfaces/ICertifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isCertifier",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICertifier__factory {
  static readonly abi = _abi;
  static createInterface(): ICertifierInterface {
    return new utils.Interface(_abi) as ICertifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICertifier {
    return new Contract(address, _abi, signerOrProvider) as ICertifier;
  }
}
