/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CurrencyRate__factory } from "./CurrencyRate__factory";
export { CurrencyStorage__factory } from "./CurrencyStorage__factory";
