/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as storages from "./storages";
export { PhoneLinkCollection__factory } from "./PhoneLinkCollection__factory";
