/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPhoneLinkCollection,
  IPhoneLinkCollectionInterface,
} from "../../../../del-osx-artifacts/contracts/interfaces/IPhoneLinkCollection";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address",
      },
    ],
    name: "nonceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_phone",
        type: "bytes32",
      },
    ],
    name: "toAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address",
      },
    ],
    name: "toPhone",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPhoneLinkCollection__factory {
  static readonly abi = _abi;
  static createInterface(): IPhoneLinkCollectionInterface {
    return new utils.Interface(_abi) as IPhoneLinkCollectionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPhoneLinkCollection {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPhoneLinkCollection;
  }
}
