/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as storages from "./storages";
export type { storages };
export type { PhoneLinkCollection } from "./PhoneLinkCollection";
