/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface LedgerStorageInterface extends utils.Interface {
  functions: {
    "MAX_FEE()": FunctionFragment;
    "bridgeAddress()": FunctionFragment;
    "burnerAddress()": FunctionFragment;
    "consumerAddress()": FunctionFragment;
    "exchangerAddress()": FunctionFragment;
    "feeAccount()": FunctionFragment;
    "foundationAccount()": FunctionFragment;
    "providerAddress()": FunctionFragment;
    "settlementAccount()": FunctionFragment;
    "tokenAddress()": FunctionFragment;
    "transferAddress()": FunctionFragment;
    "txFeeAccount()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_FEE"
      | "bridgeAddress"
      | "burnerAddress"
      | "consumerAddress"
      | "exchangerAddress"
      | "feeAccount"
      | "foundationAccount"
      | "providerAddress"
      | "settlementAccount"
      | "tokenAddress"
      | "transferAddress"
      | "txFeeAccount"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "MAX_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bridgeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "burnerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "consumerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exchangerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "foundationAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settlementAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "txFeeAccount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MAX_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchangerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "foundationAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "txFeeAccount",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LedgerStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LedgerStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_FEE(overrides?: CallOverrides): Promise<[number]>;

    bridgeAddress(overrides?: CallOverrides): Promise<[string]>;

    burnerAddress(overrides?: CallOverrides): Promise<[string]>;

    consumerAddress(overrides?: CallOverrides): Promise<[string]>;

    exchangerAddress(overrides?: CallOverrides): Promise<[string]>;

    feeAccount(overrides?: CallOverrides): Promise<[string]>;

    foundationAccount(overrides?: CallOverrides): Promise<[string]>;

    providerAddress(overrides?: CallOverrides): Promise<[string]>;

    settlementAccount(overrides?: CallOverrides): Promise<[string]>;

    tokenAddress(overrides?: CallOverrides): Promise<[string]>;

    transferAddress(overrides?: CallOverrides): Promise<[string]>;

    txFeeAccount(overrides?: CallOverrides): Promise<[string]>;
  };

  MAX_FEE(overrides?: CallOverrides): Promise<number>;

  bridgeAddress(overrides?: CallOverrides): Promise<string>;

  burnerAddress(overrides?: CallOverrides): Promise<string>;

  consumerAddress(overrides?: CallOverrides): Promise<string>;

  exchangerAddress(overrides?: CallOverrides): Promise<string>;

  feeAccount(overrides?: CallOverrides): Promise<string>;

  foundationAccount(overrides?: CallOverrides): Promise<string>;

  providerAddress(overrides?: CallOverrides): Promise<string>;

  settlementAccount(overrides?: CallOverrides): Promise<string>;

  tokenAddress(overrides?: CallOverrides): Promise<string>;

  transferAddress(overrides?: CallOverrides): Promise<string>;

  txFeeAccount(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    MAX_FEE(overrides?: CallOverrides): Promise<number>;

    bridgeAddress(overrides?: CallOverrides): Promise<string>;

    burnerAddress(overrides?: CallOverrides): Promise<string>;

    consumerAddress(overrides?: CallOverrides): Promise<string>;

    exchangerAddress(overrides?: CallOverrides): Promise<string>;

    feeAccount(overrides?: CallOverrides): Promise<string>;

    foundationAccount(overrides?: CallOverrides): Promise<string>;

    providerAddress(overrides?: CallOverrides): Promise<string>;

    settlementAccount(overrides?: CallOverrides): Promise<string>;

    tokenAddress(overrides?: CallOverrides): Promise<string>;

    transferAddress(overrides?: CallOverrides): Promise<string>;

    txFeeAccount(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    MAX_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    bridgeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    burnerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    consumerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    exchangerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    feeAccount(overrides?: CallOverrides): Promise<BigNumber>;

    foundationAccount(overrides?: CallOverrides): Promise<BigNumber>;

    providerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    settlementAccount(overrides?: CallOverrides): Promise<BigNumber>;

    tokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    transferAddress(overrides?: CallOverrides): Promise<BigNumber>;

    txFeeAccount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bridgeAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burnerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    consumerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    exchangerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeAccount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    foundationAccount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    providerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    settlementAccount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    txFeeAccount(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
