/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CurrencyRate } from "./CurrencyRate";
export type { CurrencyStorage } from "./CurrencyStorage";
