/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  PhoneStorage,
  PhoneStorageInterface,
} from "../../../../del-osx-artifacts/contracts/storages/PhoneStorage";

const _abi = [
  {
    inputs: [],
    name: "NULL",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50609b8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063f26be3fc14602d575b600080fd5b60537f32105b1d0b88ada155176b58ee08b45c31e4f2f7337475831982c313533b880c81565b60405190815260200160405180910390f3fea2646970667358221220370d53b17914f543b2c034251f9e3d7d0ed7f9fd7e97e7f3b000d4b1521ce46c64736f6c63430008020033";

type PhoneStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PhoneStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PhoneStorage__factory extends ContractFactory {
  constructor(...args: PhoneStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PhoneStorage> {
    return super.deploy(overrides || {}) as Promise<PhoneStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PhoneStorage {
    return super.attach(address) as PhoneStorage;
  }
  override connect(signer: Signer): PhoneStorage__factory {
    return super.connect(signer) as PhoneStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PhoneStorageInterface {
    return new utils.Interface(_abi) as PhoneStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PhoneStorage {
    return new Contract(address, _abi, signerOrProvider) as PhoneStorage;
  }
}
